name: tetris
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  darwin: ^0.4.1
  stanley: ^0.8.0
  console: ^4.1.0
  scidart: ^0.0.2-dev.12
  flutter_statusbarcolor: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/theme.mp3

  fonts:
    - family: PixelMix
      fonts:
        - asset: assets/fonts/pixelmix.ttf
        - asset: assets/fonts/pixelmix_bold.ttf
          weight: 700
    - family: Joystix
      fonts:
        - asset: assets/fonts/joystix.ttf

